// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { MapConfig, MapConfigTableId } from "./tables/MapConfig.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
import { Stats, StatsData, StatsTableId } from "./tables/Stats.sol";
import { Building, BuildingTableId } from "./tables/Building.sol";
import { Rock, RockTableId } from "./tables/Rock.sol";
import { Road, RoadTableId } from "./tables/Road.sol";
import { Obstruction, ObstructionTableId } from "./tables/Obstruction.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
