// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/interfaces/IBaseWorld.sol";

import { IAttackSystem } from "./IAttackSystem.sol";
import { IBuildSystem } from "./IBuildSystem.sol";
import { IGridSystem } from "./IGridSystem.sol";
import { IMoveSystem } from "./IMoveSystem.sol";
import { IStatSystem } from "./IStatSystem.sol";
import { IStructureHouseSystem } from "./IStructureHouseSystem.sol";
import { IStructureSystem } from "./IStructureSystem.sol";
import { IUnitSystem } from "./IUnitSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is
  IBaseWorld,
  IAttackSystem,
  IBuildSystem,
  IGridSystem,
  IMoveSystem,
  IStatSystem,
  IStructureHouseSystem,
  IStructureSystem,
  IUnitSystem
{

}
